### ISSUE TITLE
elastiflow-ufc - warning message level

### ISSUE THREAD

**Issue by fredtj** [elastiflow/documentation#1]
hello, thanks for ufc, i'm using it with 80+ devices so far and i've not seen any problems. logstash was previously consuming 800% cpu 100% of the time! unicolld is maxing at 13%. very pleased.

i spotted 2 slight issues:

`{"level":"fatal","ts":1608542625.259547,"caller":"nflow/config.go:75","msg":"nflow: Cannot open Maxmind ASN Database","path":"/etc/elastiflow/unicolld/maxmind/GeoLite2-ASN.mmdb","reason":"open /etc/elastiflow/unicolld/maxmind/GeoLite2-ASN.mmdb: no such file or directory","stacktrace":"github.com/elastiflow/unicolld/decoder/nflow.NewConfig\n\t/root/go/src/github.com/elastiflow/unicolld/decoder/nflow/config.go:75\nmain.main\n\t/root/go/src/github.com/elastiflow/unicolld/unicolld.go:41\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}`

it would seem the defaults for `UNICOLLD_DECODER_ENRICH_ASN_MAXMIND_ASN_PATH` and `UNICOLLD_DECODER_ENRICH_GEOIP_MAXMIND_CITY_PATH` are incorrectly documented (`/etc/elastiflow/maxmind` vs `/etc/elastiflow/unicolld/maxmind`)

is it possible to increase logging to tell which device the following message refers to?
`"level":"warn","ts":1608559737.3375793,"caller":"cached/netif.go:63","msg":"nflow: fetching interface attributes failed: request timeout (after 1 retries)"}`

Thanks again!

**Comment by lux4rd0** [comment]
I ran into the same issue - but I think it's also because there's a "full docker compose" example - and a kind of smaller docker compose example:

https://hub.docker.com/r/elastiflow/flow-collector

vs:

https://github.com/elastiflow/documentation/blob/main/unified_flow_collector/install.md

I ended up just adding some from one into the other:

      UNICOLLD_DECODER_ENRICH_ASN_MAXMIND_ASN_PATH: '/etc/elastiflow/maxmind/GeoLite2-ASN.mmdb'
      UNICOLLD_DECODER_ENRICH_GEOIP_MAXMIND_CITY_PATH: '/etc/elastiflow/maxmind/GeoLite2-City.mmdb'

But I would also agree that there's probably a default being set somewhere if those parameters are not set explicitly. :)

Once I pushed my Elastic instances up to 7.10.1 - was all good to go! Will keep testing...

_(This was mostly confirming what fredtj said - not really adding much! LOL)_

Thanks!!

**Comment by robcowart** [comment]
Hey @fredtj sorry for the delayed response. I really didn't expect anyone to open issues here, as conversations have been active on the `v5_beta` channel on the ElastiFlow community Slack. I do encourage you to join the Slack.

I am glad to hear of the greatly reduced resource consumption that you are observing over the legacy Logstash-based collector. Achieving at least 10x better throughput on the same resources (or much less resource consumption at the same throughput) was one of our primary goals.

We should be pushing a "hotfix" soon, which addresses the issues that you mention. I will add the logging enhancement you requested to the to-do list for "beta 2" which is tentatively planned for Jan 4.
